services:
  chroma_mcp:
    build:
      context: ./services/chroma_mcp
    env_file:
      - .env
    volumes:
      - ./chroma_data:/workspace/chroma
      - ./services/chroma_mcp/src:/workspace/src

  app:
    build:
      context: ./services/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - chroma_mcp
    volumes:
      - ./.chainlit:/workspace/.chainlit
      - ./public:/workspace/public
      - ./preference_data:/workspace/preferences
      - ./services/app/src:/workspace/src
      - ./attendance_data:/workspace/attendance
      - ./chroma_data:/workspace/chroma

  ingest:
    build:
      context: ./services/ingest
    env_file:
      - .env
    volumes:
      - ./data:/workspace/data
      - ./chroma_data:/workspace/chroma
      - ./services/ingest/src:/workspace/src
    restart: "no"
